# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - meilisearch
            - selenium
            - mongodb
            #            - pgsql
            #            - mariadb
            - minio
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        platform: linux/x86_64
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sailmeilisearch:/data.ms'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    selenium:
        image: 'selenium/standalone-chrome'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - sail
    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin:latest'
        links:
            - mysql:mysql
        ports:
            - 8080:80
        environment:
            MYSQL_USERNAME: "${DB_USERNAME}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: mysql
        networks:
            - sail
    mongodb:
        image: 'mongo:latest'
        restart: unless-stopped
        volumes:
            - 'sailmongodb:/mongodata'
        ports:
            - 27017:27017
        networks:
            - sail
    redisinsight:
        # use the host: host.docker.internal port 6379
        image: 'redislabs/redisinsight:latest'
        restart: unless-stopped
        ports:
            - '8001:8001'
        volumes:
            - 'sailredisinsight:/redisdata'
        networks:
            - sail
    memcached:
        image: 'memcached:alpine'
        ports:
            - '11211:11211'
        networks:
            - sail
    minio:
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9001}:9001'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8901}:8901'
        environment:
            MINIO_ROOT_USER: 'sail'
            MINIO_ROOT_PASSWORD: 'password'
        volumes:
            - 'sailminio:/data/minio'
        networks:
            - sail
        command: minio server /data/minio --console-address ":8901"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            retries: 3
            timeout: 5s
    #    pgsql:
    #        image: 'postgres:13'
    #        ports:
    #            - '${FORWARD_DB_PORT:-5432}:5432'
    #        environment:
    #            PGPASSWORD: '${DB_PASSWORD:-secret}'
    #            POSTGRES_DB: '${DB_DATABASE}'
    #            POSTGRES_USER: '${DB_USERNAME}'
    #            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    #        volumes:
    #            - 'sailpgsql:/var/lib/postgresql/data'
    #        networks:
    #            - sail
    #        healthcheck:
    #            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
    #            retries: 3
    #            timeout: 5s
    #    mariadb:
    #        image: 'mariadb:10'
    #        ports:
    #            - '${FORWARD_DB_PORT:-3306}:3306'
    #        environment:
    #            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    #            MYSQL_DATABASE: '${DB_DATABASE}'
    #            MYSQL_USER: '${DB_USERNAME}'
    #            MYSQL_PASSWORD: '${DB_PASSWORD}'
    #            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    #        volumes:
    #            - 'sailmariadb:/var/lib/mysql'
    #        networks:
    #            - sail
    #        healthcheck:
    #            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
    #            retries: 3
    #            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
    sailmeilisearch:
        driver: local
    sailmongodb:
        driver: local
    sailredisinsight:
        driver: local
    sailpgsql:
        driver: local
    sailmariadb:
        driver: local
    sailminio:
        driver: local
