<?php

namespace Database\Seeders;

use App\Models\Genre;
use Illuminate\Database\Seeder;

class GenreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seedGenres=[
            ['id'=>1, 'name'=>'Alternative', 'picture'=>'icon-alternative.png', 'parent_id'=>null],
            ['id'=>2, 'name'=>'Art Punk', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>3, 'name'=>'Alternative Rock', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>4, 'name'=>'Britpunk', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>5, 'name'=>'College Rock', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>6, 'name'=>'Crossover Thrash', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>7, 'name'=>'Crust Punk', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>8, 'name'=>'Emotional Hardcore', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>9, 'name'=>'Experimental Rock', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>10, 'name'=>'Folk Punk', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>11, 'name'=>'Goth/Gothic Rock', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>12, 'name'=>'Grunge', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>13, 'name'=>'Hardcore Punk', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>14, 'name'=>'Hard Rock', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>15, 'name'=>'Indie Rock', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>16, 'name'=>'Lo-fi', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>17, 'name'=>'Musique Concrète', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>18, 'name'=>'New Wave', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>19, 'name'=>'Progressive Rock', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>20, 'name'=>'Punk', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>21, 'name'=>'Shoegaze', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>22, 'name'=>'Steampunk', 'picture'=>'icon-alternative.png', 'parent_id'=>1],
            ['id'=>23, 'name'=>'Anime', 'picture'=>'icon-anime.png', 'parent_id'=>null],
            ['id'=>24, 'name'=>'Blues', 'picture'=>'icon-blues.png', 'parent_id'=>null],
            ['id'=>25, 'name'=>'Acoustic Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>26, 'name'=>'African Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>27, 'name'=>'Blues Rock', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>28, 'name'=>'Blues Shouter', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>29, 'name'=>'British Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>30, 'name'=>'Canadian Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>31, 'name'=>'Chicago Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>32, 'name'=>'Classic Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>33, 'name'=>'Classic Female Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>34, 'name'=>'Contemporary Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>35, 'name'=>'Contemporary R&B', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>36, 'name'=>'Country Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>37, 'name'=>'Dark Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>38, 'name'=>'Delta Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>39, 'name'=>'Detroit Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>40, 'name'=>'Doom Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>41, 'name'=>'Electric Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>42, 'name'=>'Folk Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>43, 'name'=>'Gospel Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>44, 'name'=>'Harmonica Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>45, 'name'=>'Hill Country Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>46, 'name'=>'Hokum Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>47, 'name'=>'Jazz Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>48, 'name'=>'Jump Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>49, 'name'=>'Kansas City Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>50, 'name'=>'Louisiana Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>51, 'name'=>'Memphis Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>52, 'name'=>'Modern Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>53, 'name'=>'New Orlean Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>54, 'name'=>'NY Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>55, 'name'=>'Piano Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>56, 'name'=>'Piedmont Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>57, 'name'=>'Punk Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>58, 'name'=>'Ragtime Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>59, 'name'=>'Rhythm Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>60, 'name'=>'Soul Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>61, 'name'=>'St. Louis Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>62, 'name'=>'Soul Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>63, 'name'=>'Swamp Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>64, 'name'=>'Texas Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>65, 'name'=>'Urban Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>66, 'name'=>'Vandeville', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>67, 'name'=>'West Coast Blues', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>68, 'name'=>'Zydeco', 'picture'=>'icon-blues.png', 'parent_id'=>24],
            ['id'=>69, 'name'=>'Children\'s Music', 'picture'=>'icon-childrens-music.png', 'parent_id'=>null],
            ['id'=>70, 'name'=>'Lullabies', 'picture'=>'icon-childrens-music.png', 'parent_id'=>69],
            ['id'=>71, 'name'=>'Sing-Along', 'picture'=>'icon-childrens-music.png', 'parent_id'=>69],
            ['id'=>72, 'name'=>'Stories', 'picture'=>'icon-childrens-music.png', 'parent_id'=>69],
            ['id'=>73, 'name'=>'Classical', 'picture'=>'icon-classical.png', 'parent_id'=>null],
            ['id'=>74, 'name'=>'Avant-Garde', 'picture'=>'icon-classical.png', 'parent_id'=>73],
            ['id'=>75, 'name'=>'Ballet', 'picture'=>'icon-classical.png', 'parent_id'=>73],
            ['id'=>76, 'name'=>'Baroque', 'picture'=>'icon-classical.png', 'parent_id'=>73],
            ['id'=>77, 'name'=>'Cantata', 'picture'=>'icon-classical.png', 'parent_id'=>73],
            ['id'=>78, 'name'=>'Chamber Music', 'picture'=>'icon-classical.png', 'parent_id'=>73],
            ['id'=>79, 'name'=>'String Quartet', 'picture'=>'icon-classical.png', 'parent_id'=>78],
            ['id'=>80, 'name'=>'Chant', 'picture'=>'icon-classical.png', 'parent_id'=>73],
            ['id'=>81, 'name'=>'Choral', 'picture'=>'icon-classical.png', 'parent_id'=>73],
            ['id'=>82, 'name'=>'Classical Crossover', 'picture'=>'icon-classical.png', 'parent_id'=>73],
            ['id'=>83, 'name'=>'Concerto', 'picture'=>'icon-classical.png', 'parent_id'=>73],
            ['id'=>84, 'name'=>'Concerto Grosso', 'picture'=>'icon-classical.png', 'parent_id'=>73],
            ['id'=>85, 'name'=>'Contemporary Classical', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>null],
            ['id'=>86, 'name'=>'Early Music', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>87, 'name'=>'Expressionist', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>88, 'name'=>'High Classical', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>89, 'name'=>'Impressionist', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>90, 'name'=>'Mass Requiem', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>91, 'name'=>'Medieval', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>92, 'name'=>'Minimalism', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>93, 'name'=>'Modern Composition', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>94, 'name'=>'Modern Classical', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>95, 'name'=>'Opera', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>96, 'name'=>'Oratorio', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>97, 'name'=>'Orchestral', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>98, 'name'=>'Organum', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>99, 'name'=>'Renaissance', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>100, 'name'=>'Romantic (early period)', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>101, 'name'=>'Romantic (late period)', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>102, 'name'=>'Sonata', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>103, 'name'=>'Symphonic', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>104, 'name'=>'Symphony', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>105, 'name'=>'Wedding Music', 'picture'=>'icon-contemporary-classical.png', 'parent_id'=>85],
            ['id'=>106, 'name'=>'Comedy', 'picture'=>'icon-comedy.png', 'parent_id'=>null],
            ['id'=>107, 'name'=>'Novelty', 'picture'=>'icon-comedy.png', 'parent_id'=>106],
            ['id'=>108, 'name'=>'Parody Music', 'picture'=>'icon-comedy.png', 'parent_id'=>106],
            ['id'=>109, 'name'=>'Stand-up Comedy', 'picture'=>'icon-comedy.png', 'parent_id'=>106],
            ['id'=>110, 'name'=>'Vaudeville', 'picture'=>'icon-comedy.png', 'parent_id'=>106],
            ['id'=>111, 'name'=>'Commercial', 'picture'=>'icon-commercial.png', 'parent_id'=>null],
            ['id'=>112, 'name'=>'Jingles', 'picture'=>'icon-commercial.png', 'parent_id'=>111],
            ['id'=>113, 'name'=>'TV Themes', 'picture'=>'icon-commercial.png', 'parent_id'=>111],
            ['id'=>114, 'name'=>'Country', 'picture'=>'icon-country.png', 'parent_id'=>null],
            ['id'=>115, 'name'=>'Alternative Country', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>116, 'name'=>'Americana', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>117, 'name'=>'Australian Country', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>118, 'name'=>'Bakersfield Sound', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>119, 'name'=>'Bluegrass', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>120, 'name'=>'Progressive Bluegrass', 'picture'=>'icon-country.png', 'parent_id'=>119],
            ['id'=>121, 'name'=>'Reactionary Bluegrass', 'picture'=>'icon-country.png', 'parent_id'=>119],
            ['id'=>122, 'name'=>'Blues Country', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>123, 'name'=>'Cajun Fiddle Tunes', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>124, 'name'=>'Christian Country', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>125, 'name'=>'Classic Country', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>126, 'name'=>'Close Harmony', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>127, 'name'=>'Contemporary Bluegrass', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>128, 'name'=>'Contemporary Country', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>129, 'name'=>'Country Gospel', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>130, 'name'=>'Country Pop', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>131, 'name'=>'Country Rap', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>132, 'name'=>'Country Rock', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>133, 'name'=>'Country Soul', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>134, 'name'=>'Cowboy/Western', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>135, 'name'=>'Cowpunk', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>136, 'name'=>'Dansband', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>137, 'name'=>'Honky Tonk', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>138, 'name'=>'Franco-Country', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>139, 'name'=>'Gulf and Western', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>140, 'name'=>'Hellbilly Music', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>141, 'name'=>'Honky Tonk', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>142, 'name'=>'Instrumental Country', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>143, 'name'=>'Lubbock Sound', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>144, 'name'=>'Nashville Sound', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>145, 'name'=>'Neotraditional Country', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>146, 'name'=>'Outlaw Country', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>147, 'name'=>'Progressive', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>148, 'name'=>'Psychobilly/Punkabilly', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>149, 'name'=>'Red Dirt', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>150, 'name'=>'Sertanejo', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>151, 'name'=>'Texas County', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>152, 'name'=>'Traditional Bluegrass', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>153, 'name'=>'Traditional Country', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>154, 'name'=>'Truck-Driving Country', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>155, 'name'=>'Urban Cowboy', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>156, 'name'=>'Western Swing', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>157, 'name'=>'Zydeco', 'picture'=>'icon-country.png', 'parent_id'=>114],
            ['id'=>158, 'name'=>'Dance', 'picture'=>'icon-dance.png', 'parent_id'=>null],
            ['id'=>159, 'name'=>'Club/Club Dance', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>160, 'name'=>'Breakcore', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>161, 'name'=>'Breakbeat/Breakstep', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>162, 'name'=>'4-Beat', 'picture'=>'icon-dance.png', 'parent_id'=>161],
            ['id'=>163, 'name'=>'Acid Breaks', 'picture'=>'icon-dance.png', 'parent_id'=>161],
            ['id'=>164, 'name'=>'Baltimore Club', 'picture'=>'icon-dance.png', 'parent_id'=>161],
            ['id'=>165, 'name'=>'Big Beat', 'picture'=>'icon-dance.png', 'parent_id'=>161],
            ['id'=>166, 'name'=>'Breakbeat Hardcore', 'picture'=>'icon-dance.png', 'parent_id'=>161],
            ['id'=>167, 'name'=>'Broken Beat', 'picture'=>'icon-dance.png', 'parent_id'=>161],
            ['id'=>168, 'name'=>'Florida Breaks', 'picture'=>'icon-dance.png', 'parent_id'=>161],
            ['id'=>169, 'name'=>'Nu Skool Breaks', 'picture'=>'icon-dance.png', 'parent_id'=>161],
            ['id'=>170, 'name'=>'Brostep', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>171, 'name'=>'Chillstep', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>172, 'name'=>'Deep House', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>173, 'name'=>'Dubstep', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>174, 'name'=>'Electro House', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>175, 'name'=>'Electroswing', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>176, 'name'=>'Exercise', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>177, 'name'=>'Future Garage', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>178, 'name'=>'Garage', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>179, 'name'=>'Glitch Hop', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>180, 'name'=>'Glitch Pop', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>181, 'name'=>'Grime', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>182, 'name'=>'Hardcore', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>183, 'name'=>'Bouncy House', 'picture'=>'icon-dance.png', 'parent_id'=>182],
            ['id'=>184, 'name'=>'Bouncy Techno', 'picture'=>'icon-dance.png', 'parent_id'=>182],
            ['id'=>185, 'name'=>'Breakcore', 'picture'=>'icon-dance.png', 'parent_id'=>182],
            ['id'=>186, 'name'=>'Digital Hardcore', 'picture'=>'icon-dance.png', 'parent_id'=>182],
            ['id'=>187, 'name'=>'Doomcore', 'picture'=>'icon-dance.png', 'parent_id'=>182],
            ['id'=>188, 'name'=>'Dubstyle', 'picture'=>'icon-dance.png', 'parent_id'=>182],
            ['id'=>189, 'name'=>'Gabber', 'picture'=>'icon-dance.png', 'parent_id'=>182],
            ['id'=>190, 'name'=>'Happy Hardcore', 'picture'=>'icon-dance.png', 'parent_id'=>182],
            ['id'=>191, 'name'=>'Hardstyle', 'picture'=>'icon-dance.png', 'parent_id'=>182],
            ['id'=>192, 'name'=>'Jumpstyle', 'picture'=>'icon-dance.png', 'parent_id'=>182],
            ['id'=>193, 'name'=>'Makina', 'picture'=>'icon-dance.png', 'parent_id'=>182],
            ['id'=>194, 'name'=>'Speedcore', 'picture'=>'icon-dance.png', 'parent_id'=>182],
            ['id'=>195, 'name'=>'Terrorcore', 'picture'=>'icon-dance.png', 'parent_id'=>182],
            ['id'=>196, 'name'=>'Uk Hardcore', 'picture'=>'icon-dance.png', 'parent_id'=>182],
            ['id'=>197, 'name'=>'Hard Dance', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>198, 'name'=>'Hi-NRG/Eurodance', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>199, 'name'=>'Horrorcore', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>200, 'name'=>'House', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>201, 'name'=>'Acid House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>202, 'name'=>'Chicago House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>203, 'name'=>'Deep House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>204, 'name'=>'Diva House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>205, 'name'=>'Dutch House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>206, 'name'=>'Electro House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>207, 'name'=>'Freestyle House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>208, 'name'=>'French House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>209, 'name'=>'Funky House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>210, 'name'=>'Ghetto House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>211, 'name'=>'Hardbag', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>212, 'name'=>'Hip House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>213, 'name'=>'Italo House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>214, 'name'=>'Latin House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>215, 'name'=>'Minimal House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>216, 'name'=>'Progressive House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>217, 'name'=>'Rave Music', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>218, 'name'=>'Swing House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>219, 'name'=>'Tech HouseTribal House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>220, 'name'=>'UK Hard House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>221, 'name'=>'US Garage', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>222, 'name'=>'Vocal House', 'picture'=>'icon-dance.png', 'parent_id'=>200],
            ['id'=>223, 'name'=>'Jackin House', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>224, 'name'=>'Jungle/Drum\'n\'bass', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>225, 'name'=>'Liquid Dub', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>226, 'name'=>'Regstep', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>227, 'name'=>'Speedcore', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>228, 'name'=>'Techno', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>229, 'name'=>'Acid Techno', 'picture'=>'icon-dance.png', 'parent_id'=>228],
            ['id'=>230, 'name'=>'Detroit Techno', 'picture'=>'icon-dance.png', 'parent_id'=>228],
            ['id'=>231, 'name'=>'Free Tekno', 'picture'=>'icon-dance.png', 'parent_id'=>228],
            ['id'=>232, 'name'=>'Ghettotech', 'picture'=>'icon-dance.png', 'parent_id'=>228],
            ['id'=>233, 'name'=>'Minimal', 'picture'=>'icon-dance.png', 'parent_id'=>228],
            ['id'=>234, 'name'=>'Nortec', 'picture'=>'icon-dance.png', 'parent_id'=>228],
            ['id'=>235, 'name'=>'Schranz', 'picture'=>'icon-dance.png', 'parent_id'=>228],
            ['id'=>236, 'name'=>'Techno-Dnb', 'picture'=>'icon-dance.png', 'parent_id'=>228],
            ['id'=>237, 'name'=>'Technopop', 'picture'=>'icon-dance.png', 'parent_id'=>228],
            ['id'=>238, 'name'=>'Tecno Brega', 'picture'=>'icon-dance.png', 'parent_id'=>228],
            ['id'=>239, 'name'=>'Toytown Techno', 'picture'=>'icon-dance.png', 'parent_id'=>228],
            ['id'=>240, 'name'=>'Trance', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>241, 'name'=>'Acid Trance', 'picture'=>'icon-dance.png', 'parent_id'=>240],
            ['id'=>242, 'name'=>'Classic Trance', 'picture'=>'icon-dance.png', 'parent_id'=>240],
            ['id'=>243, 'name'=>'Dream Trance', 'picture'=>'icon-dance.png', 'parent_id'=>240],
            ['id'=>244, 'name'=>'Goa Trance', 'picture'=>'icon-dance.png', 'parent_id'=>240],
            ['id'=>245, 'name'=>'Dark Psytrance', 'picture'=>'icon-dance.png', 'parent_id'=>244],
            ['id'=>246, 'name'=>'Full on', 'picture'=>'icon-dance.png', 'parent_id'=>244],
            ['id'=>247, 'name'=>'Psybreaks', 'picture'=>'icon-dance.png', 'parent_id'=>244],
            ['id'=>248, 'name'=>'Psyprog', 'picture'=>'icon-dance.png', 'parent_id'=>244],
            ['id'=>249, 'name'=>'Suomisaundi', 'picture'=>'icon-dance.png', 'parent_id'=>244],
            ['id'=>250, 'name'=>'Hard Trance', 'picture'=>'icon-dance.png', 'parent_id'=>240],
            ['id'=>251, 'name'=>'Tech Trance', 'picture'=>'icon-dance.png', 'parent_id'=>240],
            ['id'=>252, 'name'=>'Uplifting Trance', 'picture'=>'icon-dance.png', 'parent_id'=>240],
            ['id'=>253, 'name'=>'Orchestral Uplifting', 'picture'=>'icon-dance.png', 'parent_id'=>252],
            ['id'=>254, 'name'=>'Vocal Trance', 'picture'=>'icon-dance.png', 'parent_id'=>240],
            ['id'=>255, 'name'=>'Trap', 'picture'=>'icon-dance.png', 'parent_id'=>158],
            ['id'=>256, 'name'=>'Disney', 'picture'=>'icon-disney.png', 'parent_id'=>null],
            ['id'=>257, 'name'=>'Easy Listening', 'picture'=>'icon-easy-listening.png', 'parent_id'=>null],
            ['id'=>258, 'name'=>'Background', 'picture'=>'icon-easy-listening.png', 'parent_id'=>257],
            ['id'=>259, 'name'=>'Bop', 'picture'=>'icon-easy-listening.png', 'parent_id'=>257],
            ['id'=>260, 'name'=>'Elevator', 'picture'=>'icon-easy-listening.png', 'parent_id'=>257],
            ['id'=>261, 'name'=>'Furniture', 'picture'=>'icon-easy-listening.png', 'parent_id'=>257],
            ['id'=>262, 'name'=>'Lounge', 'picture'=>'icon-easy-listening.png', 'parent_id'=>257],
            ['id'=>263, 'name'=>'Middle of the Road', 'picture'=>'icon-easy-listening.png', 'parent_id'=>257],
            ['id'=>264, 'name'=>'Swing', 'picture'=>'icon-easy-listening.png', 'parent_id'=>257],
            ['id'=>265, 'name'=>'Electronic', 'picture'=>'icon-electronic.png', 'parent_id'=>null],
            ['id'=>266, 'name'=>'2-Step', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>267, 'name'=>'8-bit/8bit', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>268, 'name'=>'Ambient', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>269, 'name'=>'Ambient Dub', 'picture'=>'icon-electronic.png', 'parent_id'=>268],
            ['id'=>270, 'name'=>'Ambient House', 'picture'=>'icon-electronic.png', 'parent_id'=>268],
            ['id'=>271, 'name'=>'Ambient Techno', 'picture'=>'icon-electronic.png', 'parent_id'=>268],
            ['id'=>272, 'name'=>'Dark Ambient', 'picture'=>'icon-electronic.png', 'parent_id'=>268],
            ['id'=>273, 'name'=>'Drone Music', 'picture'=>'icon-electronic.png', 'parent_id'=>268],
            ['id'=>274, 'name'=>'Illbient', 'picture'=>'icon-electronic.png', 'parent_id'=>268],
            ['id'=>275, 'name'=>'Isolationism', 'picture'=>'icon-electronic.png', 'parent_id'=>268],
            ['id'=>276, 'name'=>'Lowercase', 'picture'=>'icon-electronic.png', 'parent_id'=>268],
            ['id'=>277, 'name'=>'Asian Underground', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>278, 'name'=>'Bassline', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>279, 'name'=>'Chillwave', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>280, 'name'=>'Chiptune', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>281, 'name'=>'Bitpop', 'picture'=>'icon-electronic.png', 'parent_id'=>280],
            ['id'=>282, 'name'=>'Game Boy', 'picture'=>'icon-electronic.png', 'parent_id'=>280],
            ['id'=>283, 'name'=>'Nintendocore', 'picture'=>'icon-electronic.png', 'parent_id'=>280],
            ['id'=>284, 'name'=>'Video Game Music', 'picture'=>'icon-electronic.png', 'parent_id'=>280],
            ['id'=>285, 'name'=>'Yorkshire Bleeps and Bass', 'picture'=>'icon-electronic.png', 'parent_id'=>280],
            ['id'=>286, 'name'=>'Crunk', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>287, 'name'=>'Downtempo', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>288, 'name'=>'Acid Jazz', 'picture'=>'icon-electronic.png', 'parent_id'=>287],
            ['id'=>289, 'name'=>'Balearic Beat', 'picture'=>'icon-electronic.png', 'parent_id'=>287],
            ['id'=>290, 'name'=>'Chill Out', 'picture'=>'icon-electronic.png', 'parent_id'=>287],
            ['id'=>291, 'name'=>'Dub Music', 'picture'=>'icon-electronic.png', 'parent_id'=>287],
            ['id'=>292, 'name'=>'Dubtronica', 'picture'=>'icon-electronic.png', 'parent_id'=>287],
            ['id'=>293, 'name'=>'Ethnic Electronica', 'picture'=>'icon-electronic.png', 'parent_id'=>287],
            ['id'=>294, 'name'=>'Moombahton', 'picture'=>'icon-electronic.png', 'parent_id'=>287],
            ['id'=>295, 'name'=>'Nu Jazz', 'picture'=>'icon-electronic.png', 'parent_id'=>287],
            ['id'=>296, 'name'=>'Trip Hop', 'picture'=>'icon-electronic.png', 'parent_id'=>287],
            ['id'=>297, 'name'=>'Drum & Bass', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>298, 'name'=>'Darkcore', 'picture'=>'icon-electronic.png', 'parent_id'=>297],
            ['id'=>299, 'name'=>'Darkstep', 'picture'=>'icon-electronic.png', 'parent_id'=>297],
            ['id'=>300, 'name'=>'Drumfunk', 'picture'=>'icon-electronic.png', 'parent_id'=>297],
            ['id'=>301, 'name'=>'Drumstep', 'picture'=>'icon-electronic.png', 'parent_id'=>297],
            ['id'=>302, 'name'=>'Hardstep', 'picture'=>'icon-electronic.png', 'parent_id'=>297],
            ['id'=>303, 'name'=>'Intelligent Drum and Bass', 'picture'=>'icon-electronic.png', 'parent_id'=>297],
            ['id'=>304, 'name'=>'Jump-Up', 'picture'=>'icon-electronic.png', 'parent_id'=>297],
            ['id'=>305, 'name'=>'Liquid Funk', 'picture'=>'icon-electronic.png', 'parent_id'=>297],
            ['id'=>306, 'name'=>'Neurofunk', 'picture'=>'icon-electronic.png', 'parent_id'=>297],
            ['id'=>307, 'name'=>'Oldschool Jungle', 'picture'=>'icon-electronic.png', 'parent_id'=>297],
            ['id'=>308, 'name'=>'Darkside Jungle', 'picture'=>'icon-electronic.png', 'parent_id'=>307],
            ['id'=>309, 'name'=>'Ragga Jungle', 'picture'=>'icon-electronic.png', 'parent_id'=>307],
            ['id'=>310, 'name'=>'Raggacore', 'picture'=>'icon-electronic.png', 'parent_id'=>297],
            ['id'=>311, 'name'=>'Sambass', 'picture'=>'icon-electronic.png', 'parent_id'=>297],
            ['id'=>312, 'name'=>'Techstep', 'picture'=>'icon-electronic.png', 'parent_id'=>297],
            ['id'=>313, 'name'=>'Electro', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>314, 'name'=>'Crunk', 'picture'=>'icon-electronic.png', 'parent_id'=>313],
            ['id'=>315, 'name'=>'Electro Backbeat', 'picture'=>'icon-electronic.png', 'parent_id'=>313],
            ['id'=>316, 'name'=>'Electro-Grime', 'picture'=>'icon-electronic.png', 'parent_id'=>313],
            ['id'=>317, 'name'=>'Electropop', 'picture'=>'icon-electronic.png', 'parent_id'=>313],
            ['id'=>318, 'name'=>'Electro-swing', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>319, 'name'=>'Electroacoustic', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>320, 'name'=>'Acousmatic Music', 'picture'=>'icon-electronic.png', 'parent_id'=>319],
            ['id'=>321, 'name'=>'Computer Music', 'picture'=>'icon-electronic.png', 'parent_id'=>319],
            ['id'=>322, 'name'=>'Electroacoustic Improvisation', 'picture'=>'icon-electronic.png', 'parent_id'=>319],
            ['id'=>323, 'name'=>'Field Recording', 'picture'=>'icon-electronic.png', 'parent_id'=>319],
            ['id'=>324, 'name'=>'Live Coding', 'picture'=>'icon-electronic.png', 'parent_id'=>319],
            ['id'=>325, 'name'=>'Live Electronics', 'picture'=>'icon-electronic.png', 'parent_id'=>319],
            ['id'=>326, 'name'=>'Soundscape Composition', 'picture'=>'icon-electronic.png', 'parent_id'=>319],
            ['id'=>327, 'name'=>'Tape Music', 'picture'=>'icon-electronic.png', 'parent_id'=>319],
            ['id'=>328, 'name'=>'Electronica', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>329, 'name'=>'Berlin School', 'picture'=>'icon-electronic.png', 'parent_id'=>328],
            ['id'=>330, 'name'=>'Chillwave', 'picture'=>'icon-electronic.png', 'parent_id'=>328],
            ['id'=>331, 'name'=>'Electronic Art Music', 'picture'=>'icon-electronic.png', 'parent_id'=>328],
            ['id'=>332, 'name'=>'Electronic Dance Music', 'picture'=>'icon-electronic.png', 'parent_id'=>328],
            ['id'=>333, 'name'=>'Folktronica', 'picture'=>'icon-electronic.png', 'parent_id'=>328],
            ['id'=>334, 'name'=>'Freestyle Music', 'picture'=>'icon-electronic.png', 'parent_id'=>328],
            ['id'=>335, 'name'=>'Glitch', 'picture'=>'icon-electronic.png', 'parent_id'=>328],
            ['id'=>336, 'name'=>'Idm', 'picture'=>'icon-electronic.png', 'parent_id'=>328],
            ['id'=>337, 'name'=>'Laptronica', 'picture'=>'icon-electronic.png', 'parent_id'=>328],
            ['id'=>338, 'name'=>'Skweee', 'picture'=>'icon-electronic.png', 'parent_id'=>328],
            ['id'=>339, 'name'=>'Sound Art', 'picture'=>'icon-electronic.png', 'parent_id'=>328],
            ['id'=>340, 'name'=>'Synthcore', 'picture'=>'icon-electronic.png', 'parent_id'=>328],
            ['id'=>341, 'name'=>'Electronic Rock', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>342, 'name'=>'Alternative Dance', 'picture'=>'icon-electronic.png', 'parent_id'=>341],
            ['id'=>343, 'name'=>'Baggy', 'picture'=>'icon-electronic.png', 'parent_id'=>342],
            ['id'=>344, 'name'=>'Madchester', 'picture'=>'icon-electronic.png', 'parent_id'=>342],
            ['id'=>345, 'name'=>'Dance-Punk', 'picture'=>'icon-electronic.png', 'parent_id'=>341],
            ['id'=>346, 'name'=>'Dance-Rock', 'picture'=>'icon-electronic.png', 'parent_id'=>341],
            ['id'=>347, 'name'=>'Dark Wave', 'picture'=>'icon-electronic.png', 'parent_id'=>341],
            ['id'=>348, 'name'=>'Electroclash', 'picture'=>'icon-electronic.png', 'parent_id'=>341],
            ['id'=>349, 'name'=>'Electronicore', 'picture'=>'icon-electronic.png', 'parent_id'=>341],
            ['id'=>350, 'name'=>'Electropunk', 'picture'=>'icon-electronic.png', 'parent_id'=>341],
            ['id'=>351, 'name'=>'Ethereal Wave', 'picture'=>'icon-electronic.png', 'parent_id'=>341],
            ['id'=>352, 'name'=>'Indietronica', 'picture'=>'icon-electronic.png', 'parent_id'=>341],
            ['id'=>353, 'name'=>'New Rave', 'picture'=>'icon-electronic.png', 'parent_id'=>341],
            ['id'=>354, 'name'=>'Space Rock', 'picture'=>'icon-electronic.png', 'parent_id'=>341],
            ['id'=>355, 'name'=>'Synthpop', 'picture'=>'icon-electronic.png', 'parent_id'=>341],
            ['id'=>356, 'name'=>'Synthpunk', 'picture'=>'icon-electronic.png', 'parent_id'=>341],
            ['id'=>357, 'name'=>'Eurodance', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>358, 'name'=>'Bubblegum Dance', 'picture'=>'icon-electronic.png', 'parent_id'=>357],
            ['id'=>359, 'name'=>'Italo Dance', 'picture'=>'icon-electronic.png', 'parent_id'=>357],
            ['id'=>360, 'name'=>'Turbofolk', 'picture'=>'icon-electronic.png', 'parent_id'=>357],
            ['id'=>361, 'name'=>'Hardstyle', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>362, 'name'=>'Hi-Nrg', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>363, 'name'=>'Eurobeat', 'picture'=>'icon-electronic.png', 'parent_id'=>362],
            ['id'=>364, 'name'=>'Hard Nrg', 'picture'=>'icon-electronic.png', 'parent_id'=>362],
            ['id'=>365, 'name'=>'New Beat', 'picture'=>'icon-electronic.png', 'parent_id'=>362],
            ['id'=>366, 'name'=>'IDM/Experimental', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>367, 'name'=>'Industrial', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>368, 'name'=>'Trip Hop', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>369, 'name'=>'UK Garage', 'picture'=>'icon-electronic.png', 'parent_id'=>265],
            ['id'=>370, 'name'=>'2-Step', 'picture'=>'icon-electronic.png', 'parent_id'=>369],
            ['id'=>371, 'name'=>'4×4', 'picture'=>'icon-electronic.png', 'parent_id'=>369],
            ['id'=>372, 'name'=>'Bassline', 'picture'=>'icon-electronic.png', 'parent_id'=>369],
            ['id'=>373, 'name'=>'Grime', 'picture'=>'icon-electronic.png', 'parent_id'=>369],
            ['id'=>374, 'name'=>'Speed Garage', 'picture'=>'icon-electronic.png', 'parent_id'=>369],
            ['id'=>375, 'name'=>'Enka', 'picture'=>'icon-enka.png', 'parent_id'=>null],
            ['id'=>376, 'name'=>'French Pop', 'picture'=>'icon-french-pop.png', 'parent_id'=>null],
            ['id'=>377, 'name'=>'Folk Music', 'picture'=>'icon-folk-music.png', 'parent_id'=>null],
            ['id'=>378, 'name'=>'American Folk Revival', 'picture'=>'icon-folk-music.png', 'parent_id'=>377],
            ['id'=>379, 'name'=>'Anti-Folk', 'picture'=>'icon-folk-music.png', 'parent_id'=>377],
            ['id'=>380, 'name'=>'British Folk Revival', 'picture'=>'icon-folk-music.png', 'parent_id'=>377],
            ['id'=>381, 'name'=>'Contemporary Folk', 'picture'=>'icon-folk-music.png', 'parent_id'=>377],
            ['id'=>382, 'name'=>'Filk Music', 'picture'=>'icon-folk-music.png', 'parent_id'=>377],
            ['id'=>383, 'name'=>'Freak Folk', 'picture'=>'icon-folk-music.png', 'parent_id'=>377],
            ['id'=>384, 'name'=>'Indie Folk', 'picture'=>'icon-folk-music.png', 'parent_id'=>377],
            ['id'=>385, 'name'=>'Industrial Folk', 'picture'=>'icon-folk-music.png', 'parent_id'=>377],
            ['id'=>386, 'name'=>'Neofolk', 'picture'=>'icon-folk-music.png', 'parent_id'=>377],
            ['id'=>387, 'name'=>'Progressive Folk', 'picture'=>'icon-folk-music.png', 'parent_id'=>377],
            ['id'=>388, 'name'=>'Psychedelic Folk', 'picture'=>'icon-folk-music.png', 'parent_id'=>377],
            ['id'=>389, 'name'=>'Sung Poetry', 'picture'=>'icon-folk-music.png', 'parent_id'=>377],
            ['id'=>390, 'name'=>'Techno-Folk', 'picture'=>'icon-folk-music.png', 'parent_id'=>377],
            ['id'=>391, 'name'=>'German Folk', 'picture'=>'icon-german-folk.png', 'parent_id'=>null],
            ['id'=>392, 'name'=>'German Pop', 'picture'=>'icon-german-pop.png', 'parent_id'=>null],
            ['id'=>393, 'name'=>'Fitness & Workout', 'picture'=>'icon-fitness-&-workout.png', 'parent_id'=>null],
            ['id'=>394, 'name'=>'Hip-Hop/Rap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>null],
            ['id'=>395, 'name'=>'Alternative Rap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>396, 'name'=>'Avant-Garde', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>397, 'name'=>'Bounce', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>398, 'name'=>'Chap Hop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>399, 'name'=>'Christian Hip Hop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>400, 'name'=>'Conscious Hip Hop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>401, 'name'=>'Country-Rap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>402, 'name'=>'Crunkcore', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>403, 'name'=>'Cumbia Rap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>404, 'name'=>'Dirty South', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>405, 'name'=>'East Coast', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>406, 'name'=>'Brick City Club', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>405],
            ['id'=>407, 'name'=>'Hardcore Hip Hop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>405],
            ['id'=>408, 'name'=>'Mafioso Rap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>405],
            ['id'=>409, 'name'=>'New Jersey Hip Hop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>405],
            ['id'=>410, 'name'=>'Freestyle Rap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>411, 'name'=>'G-Funk', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>412, 'name'=>'Gangsta Rap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>413, 'name'=>'Golden Age', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>414, 'name'=>'Hardcore Rap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>415, 'name'=>'Hip-Hop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>416, 'name'=>'Hip Pop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>417, 'name'=>'Hyphy', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>418, 'name'=>'Industrial Hip Hop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>419, 'name'=>'Instrumental Hip Hop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>420, 'name'=>'Jazz Rap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>421, 'name'=>'Latin Rap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>422, 'name'=>'Low Bap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>423, 'name'=>'Lyrical Hip Hop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>424, 'name'=>'Merenrap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>425, 'name'=>'Midwest Hip Hop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>426, 'name'=>'Chicago Hip Hop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>425],
            ['id'=>427, 'name'=>'Detroit Hip Hop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>425],
            ['id'=>428, 'name'=>'Horrorcore', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>425],
            ['id'=>429, 'name'=>'St. Louis Hip Hop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>425],
            ['id'=>430, 'name'=>'Twin Cities Hip Hop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>425],
            ['id'=>431, 'name'=>'Motswako', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>432, 'name'=>'Nerdcore', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>433, 'name'=>'New Jack Swing', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>434, 'name'=>'New School Hip Hop', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>435, 'name'=>'Old School Rap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>436, 'name'=>'Rap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>437, 'name'=>'Turntablism', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>438, 'name'=>'Underground Rap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>439, 'name'=>'West Coast Rap', 'picture'=>'icon-hip-hop-rap.png', 'parent_id'=>394],
            ['id'=>440, 'name'=>'Holiday', 'picture'=>'icon-holiday.png', 'parent_id'=>null],
            ['id'=>441, 'name'=>'Chanukah', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>442, 'name'=>'Christmas', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>443, 'name'=>'Christmas: Children\'s', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>444, 'name'=>'Christmas: Classic', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>445, 'name'=>'Christmas: Classical', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>446, 'name'=>'Christmas: Comedy', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>447, 'name'=>'Christmas: Jazz', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>448, 'name'=>'Christmas: Modern', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>449, 'name'=>'Christmas: Pop', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>450, 'name'=>'Christmas: R&B', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>451, 'name'=>'Christmas: Religious', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>452, 'name'=>'Christmas: Rock', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>453, 'name'=>'Easter', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>454, 'name'=>'Halloween', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>455, 'name'=>'Holiday: Other', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>456, 'name'=>'Thanksgiving', 'picture'=>'icon-holiday.png', 'parent_id'=>440],
            ['id'=>457, 'name'=>'Indie Pop', 'picture'=>'icon-indie-pop.png', 'parent_id'=>null],
            ['id'=>458, 'name'=>'Industrial', 'picture'=>'icon-industrial.png', 'parent_id'=>null],
            ['id'=>459, 'name'=>'Aggrotech', 'picture'=>'icon-industrial.png', 'parent_id'=>458],
            ['id'=>460, 'name'=>'Coldwave', 'picture'=>'icon-industrial.png', 'parent_id'=>458],
            ['id'=>461, 'name'=>'Cybergrind', 'picture'=>'icon-industrial.png', 'parent_id'=>458],
            ['id'=>462, 'name'=>'Dark Electro', 'picture'=>'icon-industrial.png', 'parent_id'=>458],
            ['id'=>463, 'name'=>'Death Industrial', 'picture'=>'icon-industrial.png', 'parent_id'=>458],
            ['id'=>464, 'name'=>'Electro-Industrial', 'picture'=>'icon-industrial.png', 'parent_id'=>458],
            ['id'=>465, 'name'=>'Electronic Body Music', 'picture'=>'icon-industrial.png', 'parent_id'=>458],
            ['id'=>466, 'name'=>'Futurepop', 'picture'=>'icon-industrial.png', 'parent_id'=>465],
            ['id'=>467, 'name'=>'Industrial Metal', 'picture'=>'icon-industrial.png', 'parent_id'=>458],
            ['id'=>468, 'name'=>'Neue Deutsche Härte', 'picture'=>'icon-industrial.png', 'parent_id'=>467],
            ['id'=>469, 'name'=>'Industrial Rock', 'picture'=>'icon-industrial.png', 'parent_id'=>458],
            ['id'=>470, 'name'=>'Noise', 'picture'=>'icon-industrial.png', 'parent_id'=>458],
            ['id'=>471, 'name'=>'Japanoise', 'picture'=>'icon-industrial.png', 'parent_id'=>470],
            ['id'=>472, 'name'=>'Power Electronics', 'picture'=>'icon-industrial.png', 'parent_id'=>470],
            ['id'=>473, 'name'=>'Power Noise', 'picture'=>'icon-industrial.png', 'parent_id'=>470],
            ['id'=>474, 'name'=>'Witch House', 'picture'=>'icon-industrial.png', 'parent_id'=>458],
            ['id'=>475, 'name'=>'Inspirational/Christian/Gospel', 'picture'=>'icon-inspirational-christian-gospel.png', 'parent_id'=>null],
            ['id'=>476, 'name'=>'CCM', 'picture'=>'icon-inspirational-christian-gospel.png', 'parent_id'=>475],
            ['id'=>477, 'name'=>'Christian Metal', 'picture'=>'icon-inspirational-christian-gospel.png', 'parent_id'=>475],
            ['id'=>478, 'name'=>'Christian Pop', 'picture'=>'icon-inspirational-christian-gospel.png', 'parent_id'=>475],
            ['id'=>479, 'name'=>'Christian Rap', 'picture'=>'icon-inspirational-christian-gospel.png', 'parent_id'=>475],
            ['id'=>480, 'name'=>'Christian Rock', 'picture'=>'icon-inspirational-christian-gospel.png', 'parent_id'=>475],
            ['id'=>481, 'name'=>'Classic Christian', 'picture'=>'icon-inspirational-christian-gospel.png', 'parent_id'=>475],
            ['id'=>482, 'name'=>'Contemporary Gospel', 'picture'=>'icon-inspirational-christian-gospel.png', 'parent_id'=>475],
            ['id'=>483, 'name'=>'Gospel', 'picture'=>'icon-inspirational-christian-gospel.png', 'parent_id'=>475],
            ['id'=>484, 'name'=>'Christian & Gospel', 'picture'=>'icon-inspirational-christian-gospel.png', 'parent_id'=>475],
            ['id'=>485, 'name'=>'Praise & Worship', 'picture'=>'icon-inspirational-christian-gospel.png', 'parent_id'=>475],
            ['id'=>486, 'name'=>'Qawwali', 'picture'=>'icon-inspirational-christian-gospel.png', 'parent_id'=>475],
            ['id'=>487, 'name'=>'Southern Gospel', 'picture'=>'icon-inspirational-christian-gospel.png', 'parent_id'=>475],
            ['id'=>488, 'name'=>'Traditional Gospel', 'picture'=>'icon-inspirational-christian-gospel.png', 'parent_id'=>475],
            ['id'=>489, 'name'=>'Instrumental', 'picture'=>'icon-instrumental.png', 'parent_id'=>null],
            ['id'=>490, 'name'=>'March/Marching Band', 'picture'=>'icon-instrumental.png', 'parent_id'=>489],
            ['id'=>491, 'name'=>'J-Pop', 'picture'=>'icon-j-pop.png', 'parent_id'=>null],
            ['id'=>492, 'name'=>'J-Rock', 'picture'=>'icon-j-pop.png', 'parent_id'=>491],
            ['id'=>493, 'name'=>'J-Synth', 'picture'=>'icon-j-pop.png', 'parent_id'=>491],
            ['id'=>494, 'name'=>'J-Ska', 'picture'=>'icon-j-pop.png', 'parent_id'=>491],
            ['id'=>495, 'name'=>'J-Punk', 'picture'=>'icon-j-pop.png', 'parent_id'=>491],
            ['id'=>496, 'name'=>'Jazz', 'picture'=>'icon-jazz.png', 'parent_id'=>null],
            ['id'=>497, 'name'=>'Acid Jazz (with thx to Hunter Nelson)', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>498, 'name'=>'Avant-Garde Jazz', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>499, 'name'=>'Bebop (thx Mwinogo1)', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>500, 'name'=>'Big Band', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>501, 'name'=>'Blue Note (with thx to Jillian Edwards)', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>502, 'name'=>'Contemporary Jazz', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>503, 'name'=>'Cool', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>504, 'name'=>'Crossover Jazz', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>505, 'name'=>'Dixieland', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>506, 'name'=>'Ethio-jazz (with thx to Jillian Edwards)', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>507, 'name'=>'Fusion', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>508, 'name'=>'Gypsy Jazz (kudos to Mike Tait Tafoya)', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>509, 'name'=>'Hard Bop', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>510, 'name'=>'Latin Jazz', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>511, 'name'=>'Mainstream Jazz', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>512, 'name'=>'Ragtime', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>513, 'name'=>'Smooth Jazz', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>514, 'name'=>'Trad Jazz', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>515, 'name'=>'Third Stream (cheers Benjamin Jackson-Reynolds)', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>516, 'name'=>'Jazz-Funk', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>517, 'name'=>'Free Jazz', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>518, 'name'=>'Modal Jazz', 'picture'=>'icon-jazz.png', 'parent_id'=>496],
            ['id'=>519, 'name'=>'Karaoke', 'picture'=>'icon-karaoke.png', 'parent_id'=>null],
            ['id'=>520, 'name'=>'Kayokyoku', 'picture'=>'icon-kayokyoku.png', 'parent_id'=>null],
            ['id'=>521, 'name'=>'Latin', 'picture'=>'icon-latin.png', 'parent_id'=>null],
            ['id'=>522, 'name'=>'Alternativo & Rock Latino', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>523, 'name'=>'Argentine tango', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>524, 'name'=>'Bachata', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>525, 'name'=>'Baithak Gana', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>526, 'name'=>'Baladas y Boleros', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>527, 'name'=>'Bolero', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>528, 'name'=>'Bossa Nova', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>529, 'name'=>'Brazilian', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>530, 'name'=>'Axé', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>531, 'name'=>'Bossa Nova', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>532, 'name'=>'Brazilian Rock', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>533, 'name'=>'Brega', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>534, 'name'=>'Choro', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>535, 'name'=>'Forró', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>536, 'name'=>'Frevo', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>537, 'name'=>'Funk Carioca', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>538, 'name'=>'Lambada', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>539, 'name'=>'Maracatu', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>540, 'name'=>'Música Popular Brasileira', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>541, 'name'=>'Música Sertaneja', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>542, 'name'=>'Pagode', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>543, 'name'=>'Samba', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>544, 'name'=>'Samba Rock', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>545, 'name'=>'Tecnobrega', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>546, 'name'=>'Tropicalia', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>547, 'name'=>'Zouk-Lambada', 'picture'=>'icon-latin.png', 'parent_id'=>529],
            ['id'=>548, 'name'=>'Chicha', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>549, 'name'=>'Criolla', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>550, 'name'=>'Contemporary Latin', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>551, 'name'=>'Cumbia', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>552, 'name'=>'Flamenco/Spanish Flamenco', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>553, 'name'=>'Huayno', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>554, 'name'=>'Latin Jazz', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>555, 'name'=>'Mariachi', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>556, 'name'=>'Merengue Típico', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>557, 'name'=>'Nuevo Flamenco', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>558, 'name'=>'Pop Latino', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>559, 'name'=>'Portuguese fado', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>560, 'name'=>'Punta', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>561, 'name'=>'Punta Rock', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>562, 'name'=>'Ranchera', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>563, 'name'=>'Raíces', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>564, 'name'=>'Raison', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>565, 'name'=>'Reggaeton y Hip-Hop', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>566, 'name'=>'Regional Mexicano', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>567, 'name'=>'Salsa y Tropical', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>568, 'name'=>'Soca', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>569, 'name'=>'Son', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>570, 'name'=>'Tejano', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>571, 'name'=>'Timba', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>572, 'name'=>'Twoubadou', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>573, 'name'=>'Zouk', 'picture'=>'icon-latin.png', 'parent_id'=>521],
            ['id'=>574, 'name'=>'Metal', 'picture'=>'icon-metal.png', 'parent_id'=>null],
            ['id'=>575, 'name'=>'Heavy Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>576, 'name'=>'Speed Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>577, 'name'=>'Thrash Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>578, 'name'=>'Power Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>579, 'name'=>'Death Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>580, 'name'=>'Black Metall', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>581, 'name'=>'Pagan Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>582, 'name'=>'Viking Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>583, 'name'=>'Folk Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>584, 'name'=>'Symphonic Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>585, 'name'=>'Gothic Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>586, 'name'=>'Glam Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>587, 'name'=>'Hair Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>588, 'name'=>'Doom Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>589, 'name'=>'Groove Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>590, 'name'=>'Industrial Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>591, 'name'=>'Modern Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>592, 'name'=>'Neoclassical Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>593, 'name'=>'New Wave Of British Heavy Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>594, 'name'=>'Post Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>595, 'name'=>'Progressive Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>596, 'name'=>'Avantgarde Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>597, 'name'=>'Sludge', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>598, 'name'=>'Djent', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>599, 'name'=>'Drone', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>600, 'name'=>'Kawaii Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>601, 'name'=>'Pirate Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>602, 'name'=>'Nu Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>603, 'name'=>'Neue Deutsche Härte', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>604, 'name'=>'Math Metal', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>605, 'name'=>'Crossover', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>606, 'name'=>'Grindcore', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>607, 'name'=>'Hardcore', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>608, 'name'=>'Metalcore', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>609, 'name'=>'Deathcore', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>610, 'name'=>'Post Hardcore', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>611, 'name'=>'Mathcore', 'picture'=>'icon-metal.png', 'parent_id'=>574],
            ['id'=>612, 'name'=>'New Age', 'picture'=>'icon-new-age.png', 'parent_id'=>null],
            ['id'=>613, 'name'=>'Environmental', 'picture'=>'icon-new-age.png', 'parent_id'=>612],
            ['id'=>614, 'name'=>'Healing', 'picture'=>'icon-new-age.png', 'parent_id'=>612],
            ['id'=>615, 'name'=>'Meditation', 'picture'=>'icon-new-age.png', 'parent_id'=>612],
            ['id'=>616, 'name'=>'Nature', 'picture'=>'icon-new-age.png', 'parent_id'=>612],
            ['id'=>617, 'name'=>'Relaxation', 'picture'=>'icon-new-age.png', 'parent_id'=>612],
            ['id'=>618, 'name'=>'Travel', 'picture'=>'icon-new-age.png', 'parent_id'=>612],
            ['id'=>619, 'name'=>'Opera', 'picture'=>'icon-opera.png', 'parent_id'=>null],
            ['id'=>620, 'name'=>'Pop', 'picture'=>'icon-pop.png', 'parent_id'=>null],
            ['id'=>621, 'name'=>'Adult Contemporary', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>622, 'name'=>'Arab Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>623, 'name'=>'Baroque', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>624, 'name'=>'Britpop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>625, 'name'=>'Bubblegum Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>626, 'name'=>'Chamber Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>627, 'name'=>'Chanson', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>628, 'name'=>'Christian Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>629, 'name'=>'Classical Crossover', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>630, 'name'=>'Europop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>631, 'name'=>'Austropop', 'picture'=>'icon-pop.png', 'parent_id'=>630],
            ['id'=>632, 'name'=>'Balkan Pop', 'picture'=>'icon-pop.png', 'parent_id'=>630],
            ['id'=>633, 'name'=>'French Pop', 'picture'=>'icon-pop.png', 'parent_id'=>630],
            ['id'=>634, 'name'=>'Latin Pop', 'picture'=>'icon-pop.png', 'parent_id'=>630],
            ['id'=>635, 'name'=>'Laïkó', 'picture'=>'icon-pop.png', 'parent_id'=>630],
            ['id'=>636, 'name'=>'Nederpop', 'picture'=>'icon-pop.png', 'parent_id'=>630],
            ['id'=>637, 'name'=>'Russian Pop', 'picture'=>'icon-pop.png', 'parent_id'=>630],
            ['id'=>638, 'name'=>'Dance Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>639, 'name'=>'Dream Pop ', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>640, 'name'=>'Electro Pop ', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>641, 'name'=>'Iranian Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>642, 'name'=>'Jangle Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>643, 'name'=>'Latin Ballad', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>644, 'name'=>'Levenslied', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>645, 'name'=>'Louisiana Swamp Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>646, 'name'=>'Mexican Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>647, 'name'=>'Motorpop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>648, 'name'=>'New Romanticism', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>649, 'name'=>'Orchestral Pop ', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>650, 'name'=>'Pop Rap', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>651, 'name'=>'Popera', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>652, 'name'=>'Pop/Rock', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>653, 'name'=>'Pop Punk ', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>654, 'name'=>'Power Pop ', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>655, 'name'=>'Psychedelic Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>656, 'name'=>'Schlager', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>657, 'name'=>'Soft Rock', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>658, 'name'=>'Sophisti-Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>659, 'name'=>'Space Age Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>660, 'name'=>'Sunshine Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>661, 'name'=>'Surf Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>662, 'name'=>'Synthpop ', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>663, 'name'=>'Teen Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>664, 'name'=>'Traditional Pop Music', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>665, 'name'=>'Turkish Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>666, 'name'=>'Vispop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>667, 'name'=>'Wonky Pop', 'picture'=>'icon-pop.png', 'parent_id'=>620],
            ['id'=>668, 'name'=>'Post-Disco', 'picture'=>'icon-post-disco.png', 'parent_id'=>null],
            ['id'=>669, 'name'=>'Boogie', 'picture'=>'icon-post-disco.png', 'parent_id'=>668],
            ['id'=>670, 'name'=>'Dance-pop', 'picture'=>'icon-post-disco.png', 'parent_id'=>668],
            ['id'=>671, 'name'=>'Progressive', 'picture'=>'icon-progressive.png', 'parent_id'=>null],
            ['id'=>672, 'name'=>'Progressive House/Trance', 'picture'=>'icon-progressive.png', 'parent_id'=>671],
            ['id'=>673, 'name'=>'Disco House', 'picture'=>'icon-progressive.png', 'parent_id'=>672],
            ['id'=>674, 'name'=>'Dream House', 'picture'=>'icon-progressive.png', 'parent_id'=>672],
            ['id'=>675, 'name'=>'Space House', 'picture'=>'icon-progressive.png', 'parent_id'=>672],
            ['id'=>676, 'name'=>'Japanese House', 'picture'=>'icon-progressive.png', 'parent_id'=>672],
            ['id'=>677, 'name'=>'Bounce/Scouse House', 'picture'=>'icon-progressive.png', 'parent_id'=>672],
            ['id'=>678, 'name'=>'Progressive Breaks', 'picture'=>'icon-progressive.png', 'parent_id'=>671],
            ['id'=>679, 'name'=>'Progressive Drum & Bass', 'picture'=>'icon-progressive.png', 'parent_id'=>671],
            ['id'=>680, 'name'=>'Progressive Techno', 'picture'=>'icon-progressive.png', 'parent_id'=>671],
            ['id'=>681, 'name'=>'R&B/Soul', 'picture'=>'icon-r&b-soul.png', 'parent_id'=>null],
            ['id'=>682, 'name'=>'Contemporary R&B', 'picture'=>'icon-r&b-soul.png', 'parent_id'=>681],
            ['id'=>683, 'name'=>'Disco', 'picture'=>'icon-r&b-soul.png', 'parent_id'=>681],
            ['id'=>684, 'name'=>'Doo Wop', 'picture'=>'icon-r&b-soul.png', 'parent_id'=>681],
            ['id'=>685, 'name'=>'Funk', 'picture'=>'icon-r&b-soul.png', 'parent_id'=>681],
            ['id'=>686, 'name'=>'Modern Soul', 'picture'=>'icon-r&b-soul.png', 'parent_id'=>681],
            ['id'=>687, 'name'=>'Motown', 'picture'=>'icon-r&b-soul.png', 'parent_id'=>681],
            ['id'=>688, 'name'=>'Neo-Soul', 'picture'=>'icon-r&b-soul.png', 'parent_id'=>681],
            ['id'=>689, 'name'=>'Northern Soul', 'picture'=>'icon-r&b-soul.png', 'parent_id'=>681],
            ['id'=>690, 'name'=>'Psychedelic Soul ', 'picture'=>'icon-r&b-soul.png', 'parent_id'=>681],
            ['id'=>691, 'name'=>'Quiet Storm', 'picture'=>'icon-r&b-soul.png', 'parent_id'=>681],
            ['id'=>692, 'name'=>'Soul', 'picture'=>'icon-r&b-soul.png', 'parent_id'=>681],
            ['id'=>693, 'name'=>'Soul Blues ', 'picture'=>'icon-r&b-soul.png', 'parent_id'=>681],
            ['id'=>694, 'name'=>'Southern Soul ', 'picture'=>'icon-r&b-soul.png', 'parent_id'=>681],
            ['id'=>695, 'name'=>'Reggae', 'picture'=>'icon-reggae.png', 'parent_id'=>null],
            ['id'=>696, 'name'=>'2-Tone', 'picture'=>'icon-reggae.png', 'parent_id'=>695],
            ['id'=>697, 'name'=>'Dancehall', 'picture'=>'icon-reggae.png', 'parent_id'=>695],
            ['id'=>698, 'name'=>'Dub', 'picture'=>'icon-reggae.png', 'parent_id'=>695],
            ['id'=>699, 'name'=>'Roots Reggae', 'picture'=>'icon-reggae.png', 'parent_id'=>695],
            ['id'=>700, 'name'=>'Reggae Fusion', 'picture'=>'icon-reggae.png', 'parent_id'=>695],
            ['id'=>701, 'name'=>'Reggae en Español', 'picture'=>'icon-reggae.png', 'parent_id'=>695],
            ['id'=>702, 'name'=>'Spanish Reggae', 'picture'=>'icon-reggae.png', 'parent_id'=>701],
            ['id'=>703, 'name'=>'Reggae 110', 'picture'=>'icon-reggae.png', 'parent_id'=>701],
            ['id'=>704, 'name'=>'Reggae Bultrón', 'picture'=>'icon-reggae.png', 'parent_id'=>701],
            ['id'=>705, 'name'=>'Romantic Flow', 'picture'=>'icon-reggae.png', 'parent_id'=>701],
            ['id'=>706, 'name'=>'Lovers Rock', 'picture'=>'icon-reggae.png', 'parent_id'=>695],
            ['id'=>707, 'name'=>'Raggamuffin', 'picture'=>'icon-reggae.png', 'parent_id'=>695],
            ['id'=>708, 'name'=>'Ragga', 'picture'=>'icon-reggae.png', 'parent_id'=>707],
            ['id'=>709, 'name'=>'Dancehall', 'picture'=>'icon-reggae.png', 'parent_id'=>707],
            ['id'=>710, 'name'=>'Ska', 'picture'=>'icon-reggae.png', 'parent_id'=>695],
            ['id'=>711, 'name'=>'2 Tone', 'picture'=>'icon-reggae.png', 'parent_id'=>710],
            ['id'=>712, 'name'=>'Dub', 'picture'=>'icon-reggae.png', 'parent_id'=>710],
            ['id'=>713, 'name'=>'Rocksteady', 'picture'=>'icon-reggae.png', 'parent_id'=>710],
            ['id'=>714, 'name'=>'Rock', 'picture'=>'icon-rock.png', 'parent_id'=>null],
            ['id'=>715, 'name'=>'Acid Rock ', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>716, 'name'=>'Adult-Oriented Rock ', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>717, 'name'=>'Afro Punk', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>718, 'name'=>'Adult Alternative', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>719, 'name'=>'Alternative Rock ', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>720, 'name'=>'American Traditional Rock', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>721, 'name'=>'Anatolian Rock', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>722, 'name'=>'Arena Rock', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>723, 'name'=>'Art Rock', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>724, 'name'=>'Blues-Rock', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>725, 'name'=>'British Invasion', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>726, 'name'=>'Cock Rock', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>727, 'name'=>'Death Metal/Black Metal', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>728, 'name'=>'Doom Metal ', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>729, 'name'=>'Glam Rock', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>730, 'name'=>'Gothic Metal ', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>731, 'name'=>'Grind Core', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>732, 'name'=>'Hair Metal', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>733, 'name'=>'Hard Rock', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>734, 'name'=>'Math Metal', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>735, 'name'=>'Math Rock ', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>736, 'name'=>'Metal', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>737, 'name'=>'Metal Core ', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>738, 'name'=>'Noise Rock/Japanoise', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>739, 'name'=>'Jam Bands', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>740, 'name'=>'Post Punk', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>741, 'name'=>'Prog-Rock/Art Rock', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>742, 'name'=>'Progressive Metal ', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>743, 'name'=>'Psychedelic', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>744, 'name'=>'Rock & Roll', 'picture'=>'icon-rock.png', 'parent_id'=>714],
            ['id'=>745, 'name'=>'Rockabilly', 'picture'=>'icon-rockabilly.png', 'parent_id'=>null],
            ['id'=>746, 'name'=>'Roots Rock', 'picture'=>'icon-rockabilly.png', 'parent_id'=>745],
            ['id'=>747, 'name'=>'Singer/Songwriter', 'picture'=>'icon-rockabilly.png', 'parent_id'=>745],
            ['id'=>748, 'name'=>'Southern Rock', 'picture'=>'icon-rockabilly.png', 'parent_id'=>745],
            ['id'=>749, 'name'=>'Spazzcore ', 'picture'=>'icon-rockabilly.png', 'parent_id'=>745],
            ['id'=>750, 'name'=>'Stoner Metal', 'picture'=>'icon-rockabilly.png', 'parent_id'=>745],
            ['id'=>751, 'name'=>'Surf', 'picture'=>'icon-rockabilly.png', 'parent_id'=>745],
            ['id'=>752, 'name'=>'Technical Death Metal ', 'picture'=>'icon-rockabilly.png', 'parent_id'=>745],
            ['id'=>753, 'name'=>'Tex-Mex', 'picture'=>'icon-rockabilly.png', 'parent_id'=>745],
            ['id'=>754, 'name'=>'Thrash Metal ', 'picture'=>'icon-rockabilly.png', 'parent_id'=>745],
            ['id'=>755, 'name'=>'Time Lord Rock (Trock) ', 'picture'=>'icon-rockabilly.png', 'parent_id'=>745],
            ['id'=>756, 'name'=>'Trip-hop ', 'picture'=>'icon-rockabilly.png', 'parent_id'=>745],
            ['id'=>757, 'name'=>'Singer/Songwriter', 'picture'=>'icon-singer-songwriter.png', 'parent_id'=>null],
            ['id'=>758, 'name'=>'Alternative Folk', 'picture'=>'icon-singer-songwriter.png', 'parent_id'=>757],
            ['id'=>759, 'name'=>'Contemporary Folk', 'picture'=>'icon-singer-songwriter.png', 'parent_id'=>757],
            ['id'=>760, 'name'=>'Contemporary Singer/Songwriter', 'picture'=>'icon-singer-songwriter.png', 'parent_id'=>757],
            ['id'=>761, 'name'=>'Indie Folk (with thanks to Andrew Barrett)', 'picture'=>'icon-singer-songwriter.png', 'parent_id'=>757],
            ['id'=>762, 'name'=>'Folk-Rock', 'picture'=>'icon-singer-songwriter.png', 'parent_id'=>757],
            ['id'=>763, 'name'=>'Love Song (Chanson – merci Marcel Borchert)', 'picture'=>'icon-singer-songwriter.png', 'parent_id'=>757],
            ['id'=>764, 'name'=>'New Acoustic', 'picture'=>'icon-singer-songwriter.png', 'parent_id'=>757],
            ['id'=>765, 'name'=>'Traditional Folk', 'picture'=>'icon-singer-songwriter.png', 'parent_id'=>757],
            ['id'=>766, 'name'=>'Soundtrack', 'picture'=>'icon-soundtrack.png', 'parent_id'=>null],
            ['id'=>767, 'name'=>'Foreign Cinema', 'picture'=>'icon-soundtrack.png', 'parent_id'=>766],
            ['id'=>768, 'name'=>'Movie Soundtrack (thanks Julien)', 'picture'=>'icon-soundtrack.png', 'parent_id'=>766],
            ['id'=>769, 'name'=>'Musicals', 'picture'=>'icon-soundtrack.png', 'parent_id'=>766],
            ['id'=>770, 'name'=>'Original Score', 'picture'=>'icon-soundtrack.png', 'parent_id'=>766],
            ['id'=>771, 'name'=>'Soundtrack', 'picture'=>'icon-soundtrack.png', 'parent_id'=>766],
            ['id'=>772, 'name'=>'TV Soundtrack', 'picture'=>'icon-soundtrack.png', 'parent_id'=>766],
            ['id'=>773, 'name'=>'Spoken Word', 'picture'=>'icon-spoken-word.png', 'parent_id'=>null],
            ['id'=>774, 'name'=>'Tex-Mex/Tejano (with thx to Israel Lopez)', 'picture'=>'icon-tex-mex---tejano (with-thx-to-israel-lopez).png', 'parent_id'=>null],
            ['id'=>775, 'name'=>'Chicano', 'picture'=>'icon-tex-mex---tejano (with-thx-to-israel-lopez).png', 'parent_id'=>774],
            ['id'=>776, 'name'=>'Classic', 'picture'=>'icon-tex-mex---tejano (with-thx-to-israel-lopez).png', 'parent_id'=>774],
            ['id'=>777, 'name'=>'Conjunto', 'picture'=>'icon-tex-mex---tejano (with-thx-to-israel-lopez).png', 'parent_id'=>774],
            ['id'=>778, 'name'=>'Conjunto Progressive', 'picture'=>'icon-tex-mex---tejano (with-thx-to-israel-lopez).png', 'parent_id'=>774],
            ['id'=>779, 'name'=>'New Mex', 'picture'=>'icon-tex-mex---tejano (with-thx-to-israel-lopez).png', 'parent_id'=>774],
            ['id'=>780, 'name'=>'Tex-Mex', 'picture'=>'icon-tex-mex---tejano (with-thx-to-israel-lopez).png', 'parent_id'=>774],
            ['id'=>781, 'name'=>'Vocal', 'picture'=>'icon-vocal.png', 'parent_id'=>null],
            ['id'=>782, 'name'=>'A cappella (with kudos to Sheldon Reynolds)', 'picture'=>'icon-vocal.png', 'parent_id'=>781],
            ['id'=>783, 'name'=>'Barbershop (with thx to Kelly Chism)', 'picture'=>'icon-vocal.png', 'parent_id'=>781],
            ['id'=>784, 'name'=>'Cantique (sacred vocal)', 'picture'=>'icon-vocal.png', 'parent_id'=>781],
            ['id'=>785, 'name'=>'Doo-wop (with thx to Bradley Thompson)', 'picture'=>'icon-vocal.png', 'parent_id'=>781],
            ['id'=>786, 'name'=>'Gregorian Chant (hat tip to Deborah Knight-Nikifortchuk)', 'picture'=>'icon-vocal.png', 'parent_id'=>781],
            ['id'=>787, 'name'=>'Standards', 'picture'=>'icon-vocal.png', 'parent_id'=>781],
            ['id'=>788, 'name'=>'Traditional Pop', 'picture'=>'icon-vocal.png', 'parent_id'=>781],
            ['id'=>789, 'name'=>'Vocal Jazz', 'picture'=>'icon-vocal.png', 'parent_id'=>781],
            ['id'=>790, 'name'=>'Vocal Pop', 'picture'=>'icon-vocal.png', 'parent_id'=>781],
            ['id'=>791, 'name'=>'World', 'picture'=>'icon-world.png', 'parent_id'=>null],
            ['id'=>792, 'name'=>'Africa', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>793, 'name'=>'African Heavy Metal', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>794, 'name'=>'African Hip Hop', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>795, 'name'=>'Afro-Beat', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>796, 'name'=>'Afro-Pop', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>797, 'name'=>'Apala', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>798, 'name'=>'Benga', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>799, 'name'=>'Bikutsi', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>800, 'name'=>'Bongo Flava', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>801, 'name'=>'Cape Jazz', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>802, 'name'=>'Chimurenga', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>803, 'name'=>'Coupé-Décalé', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>804, 'name'=>'Fuji Music', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>805, 'name'=>'Genge', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>806, 'name'=>'Highlife', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>807, 'name'=>'Hiplife', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>808, 'name'=>'Isicathamiya', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>809, 'name'=>'Jit', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>810, 'name'=>'Jùjú', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>811, 'name'=>'Kapuka', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>812, 'name'=>'Kizomba', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>813, 'name'=>'Kuduro', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>814, 'name'=>'Kwaito', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>815, 'name'=>'Kwela', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>816, 'name'=>'Makossa', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>817, 'name'=>'Maloya', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>818, 'name'=>'Marrabenta', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>819, 'name'=>'Mbalax', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>820, 'name'=>'Mbaqanga', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>821, 'name'=>'Mbube', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>822, 'name'=>'Morna', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>823, 'name'=>'Museve', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>824, 'name'=>'Palm-Wine', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>825, 'name'=>'Raï', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>826, 'name'=>'Sakara', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>827, 'name'=>'Sega', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>828, 'name'=>'Seggae', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>829, 'name'=>'Semba', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>830, 'name'=>'Soukous', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>831, 'name'=>'Taarab', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>832, 'name'=>'Zouglou', 'picture'=>'icon-world.png', 'parent_id'=>792],
            ['id'=>833, 'name'=>'Asia', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>834, 'name'=>'Anison', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>835, 'name'=>'C-Pop', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>836, 'name'=>'Cantopop', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>837, 'name'=>'Enka', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>838, 'name'=>'Hong Kong English Pop', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>839, 'name'=>'Fann At-Tanbura', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>840, 'name'=>'Fijiri', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>841, 'name'=>'J-Pop', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>842, 'name'=>'Japanese Pop', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>843, 'name'=>'K-Pop', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>844, 'name'=>'Khaliji', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>845, 'name'=>'Kayōkyoku', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>846, 'name'=>'Korean Pop', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>847, 'name'=>'Liwa', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>848, 'name'=>'Mandopop', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>849, 'name'=>'Onkyokei', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>850, 'name'=>'Taiwanese Pop', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>851, 'name'=>'Sawt', 'picture'=>'icon-world.png', 'parent_id'=>833],
            ['id'=>852, 'name'=>'Australia', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>853, 'name'=>'Cajun', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>854, 'name'=>'Calypso ', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>855, 'name'=>'Caribbean', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>856, 'name'=>'Chutney', 'picture'=>'icon-world.png', 'parent_id'=>855],
            ['id'=>857, 'name'=>'Chutney Soca', 'picture'=>'icon-world.png', 'parent_id'=>855],
            ['id'=>858, 'name'=>'Compas', 'picture'=>'icon-world.png', 'parent_id'=>855],
            ['id'=>859, 'name'=>'Mambo', 'picture'=>'icon-world.png', 'parent_id'=>855],
            ['id'=>860, 'name'=>'Merengue', 'picture'=>'icon-world.png', 'parent_id'=>855],
            ['id'=>861, 'name'=>'Méringue', 'picture'=>'icon-world.png', 'parent_id'=>855],
            ['id'=>862, 'name'=>'Carnatic (Karnataka Sanghetha)', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>863, 'name'=>'Celtic', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>864, 'name'=>'Celtic Folk', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>865, 'name'=>'Contemporary Celtic', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>866, 'name'=>'Coupé-décalé (Congo)', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>867, 'name'=>'Dangdut', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>868, 'name'=>'Drinking Songs', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>869, 'name'=>'Drone', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>870, 'name'=>'Europe', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>871, 'name'=>'France', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>872, 'name'=>'Hawaii', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>873, 'name'=>'Japan', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>874, 'name'=>'Klezmer', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>875, 'name'=>'Mbalax (Senegal)', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>876, 'name'=>'Middle East', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>877, 'name'=>'North America', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>878, 'name'=>'Ode ', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>879, 'name'=>'Piphat (Thailand)', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>880, 'name'=>'Polka', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>881, 'name'=>'Soca ', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>882, 'name'=>'South Africa', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>883, 'name'=>'South America', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>884, 'name'=>'South/Southeast Asia', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>885, 'name'=>'Baila', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>886, 'name'=>'Bhangra', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>887, 'name'=>'Bhojpuri', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>888, 'name'=>'Dangdut', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>889, 'name'=>'Filmi', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>890, 'name'=>'Indian Pop', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>891, 'name'=>'Hindustani', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>892, 'name'=>'Indian Ghazal', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>893, 'name'=>'Lavani', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>894, 'name'=>'Luk Thung', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>895, 'name'=>'Luk Krung', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>896, 'name'=>'Manila Sound', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>897, 'name'=>'Morlam', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>898, 'name'=>'Pinoy Pop', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>899, 'name'=>'Pop Sunda', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>900, 'name'=>'Ragini', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>901, 'name'=>'Thai Pop', 'picture'=>'icon-world.png', 'parent_id'=>884],
            ['id'=>902, 'name'=>'Traditional Celtic', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>903, 'name'=>'Worldbeat', 'picture'=>'icon-world.png', 'parent_id'=>791],
            ['id'=>904, 'name'=>'Zydeco', 'picture'=>'icon-world.png', 'parent_id'=>791],
        ];

        foreach ($seedGenres as $seed) {
            Genre::create($seed);
        }
    }
}
